global:
  scrape_interval:     10s
  evaluation_interval: 15s

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'docker-host-alpha'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - "alert.rules"

# A scrape configuration containing exactly one endpoint to scrape.
scrape_configs:
  - job_name: "ha"
    scrape_interval: 60s
    metrics_path: /api/prometheus

    # Long-Lived Access Token
    bearer_token: "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiIzNDA5NzE3MzY3NTc0ZjcwOTU0MDBjMTMwZWU1YTg2NiIsImlhdCI6MTY1OTkxNTU1MSwiZXhwIjoxOTc1Mjc1NTUxfQ.1-HYJlgslbx7yTA0g1MGbz3Gq8pgZERwmp9tPsulcHM"

    scheme: https
    static_configs:
      - targets: ['192.168.1.2:8123']

  - job_name: 'nodeexporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['nodeexporter:9100']

  - job_name: 'cadvisor'
    scrape_interval: 5s
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'nginx-external'
    static_configs:
      - targets: ['nginx-exporter-external:9113']

  - job_name: 'nginx-internal'
    static_configs:
      - targets: ['nginx-exporter-internal:9113']

  # - job_name: 'pushgateway'
  #   scrape_interval: 10s
  #   honor_labels: true
  #   static_configs:
  #     - targets: ['pushgateway:9091']


# alerting:
#   alertmanagers:
#   - scheme: http
#     static_configs:
#     - targets: 
#       - 'alertmanager:9093'

